basePath: '{{.BasePath}}'
definitions:
  model.Response:
    properties:
      quote:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /fallout/raider:
    get:
      description: Get a random quote from a Raider NPC
      operationId: raider
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
            type: object
      summary: Raider quotes
  /plots/christmas:
    get:
      description: Generate a random, whacky Christmas movie plot
      operationId: christmas-plots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
            type: object
      summary: Randomized Christmas movie plots
  /status:
    get:
      description: Status check
      operationId: status
      produces:
      - application/json
      responses:
        "200": {}
      summary: Health check URL
  /trd/pikachu:
    get:
      description: Find out what your face is
      operationId: your-face
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
            type: object
      summary: Patrick Carver Simulation Machine
swagger: "2.0"
