package quotes

var Raider = []string{"Tell me the truth, Joe... does this coat make me look fat?",
	"So does the flame thrower really get the chicks?",
	"Touch me again and I cut off your balls!",
	"Heh heh. She wants me.",
	"Just do your goddamn job and shut your mouth!",
	"Pain! Pain is your only friend!",
	"I'm gonna mount you on my fucking wall!",
	"Should have stayed in bed today, hero!",
	"Are you gonna cry? Come on, cry for me!",
	"That's right. Love the pain! Embrace the pain!",
	"Aggghhh!",
	"...too fuckin' quiet...",
	"...can't keep doing this forever... one last haul, then I'll call it quits...",
	"...*sigh* need a drink... the real shit, not moonshine...",
	"...gotta be an end to this someday... for now, gotta do what I gotta do...",
	"Gah! Blood in my eyes!",
	"Ha. What a little bitch.",
	"Where'd that little fucker go?",
	",Keep your eyes open. I think this asshole's using a Stealth Boy",
	"And that's how you survive in the Commonwealth, asshole.",
	"I need a fuckin' drink.",
	"Whoa, whoa. Shut the fuck up a second. I hear something",
	"Scared, just like a little bitch.",
}
