// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-11 17:33:09.191069026 -0500 EST m=+0.041629091

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fallout/raider": {
            "get": {
                "description": "Get a random quote from a Raider NPC",
                "produces": [
                    "application/json"
                ],
                "summary": "Raider quotes",
                "operationId": "raider",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/plots/christmas": {
            "get": {
                "description": "Generate a random, whacky Christmas movie plot",
                "produces": [
                    "application/json"
                ],
                "summary": "Randomized Christmas movie plots",
                "operationId": "christmas-plots",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Status check",
                "produces": [
                    "application/json"
                ],
                "summary": "Health check URL",
                "operationId": "status",
                "responses": {
                    "200": {}
                }
            }
        },
        "/trd/pikachu": {
            "get": {
                "description": "Find out what your face is",
                "produces": [
                    "application/json"
                ],
                "summary": "Patrick Carver Simulation Machine",
                "operationId": "your-face",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Response": {
            "type": "object",
            "properties": {
                "quote": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
